spring:
  application:
    name: bigdata
  profiles:
    active: dev
  kafka:
    bootstrap-servers: 10.211.55.5:9092
    template:
      default-topic: kafka-test
    producer:
      acks: all
      retries: 0
      batch-size: 16384
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      session-timeout: 30000
      group-id: group-test
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: earliest
      max-poll-records: 10
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      poll-timeout: 3000


server:
  port: 8080

# zookeeper
zookeeper:
  # 启用状态
  enable: true
  # 服务器地址
  address: 10.211.55.5:2181
  # 命名空间
  namespace: zk-test
  #权限控制，加密
  digest: parallels:123456
  # 会话超时时间
  sessionTimeoutMs: 5000
  # 连接超时时间
  connectionTimeoutMs: 60000
  # 最大重试次数
  maxRetries: 3
  # 初始休眠时间
  baseSleepTimeMs: 1000

# canal
canal:
  user: canal
  password: canal
  destination: example
  single:
    host: 10.211.55.5
    port: 11111
