# 启动
nohup ./bin/kafka-server-start.sh ./config/server.properties > kafka.log 2>&1 &

# 停止
./bin/kafka-server-stop.sh ./config/server.properties

# 创建topic
./bin/kafka-topics.sh --create --zookeeper 10.211.55.5:2181/kafka --replication-factor 1 --partitions 1 --topic kafka-test

# 删除topic
./bin/kafka-topics.sh --zookeeper 10.211.55.5:2181/kafka --delete --topic kafka-test

# 查看topic
./bin/kafka-topics.sh --list --zookeeper 10.211.55.5:2181/kafka

# 查看topic详情
./bin/kafka-topics.sh --describe --zookeeper 10.211.55.5:2181/kafka --topic kafka-test

# 发送消息
./bin/kafka-console-producer.sh --broker-list 10.211.55.5:9092 --topic kafka-test

# 消费消息
./bin/kafka-console-consumer.sh --bootstrap-server 10.211.55.5:9092 --topic kafka-test [--from-beginning]

# 查看消费组
./bin/kafka-consumer-groups.sh --zookeeper 10.211.55.5:2181/kafka --list
./bin/kafka-consumer-groups.sh --bootstrap-server 10.211.55.5:9092 --list

# 查看消费组详情
./bin/kafka-consumer-groups.sh --bootstrap-server 10.211.55.5:9092 --describe --group [group_name] [--state|--members|--verbose]

# 删除消费组
./bin/kafka-consumer-groups.sh --bootstrap-server 10.211.55.5:9092 --delete --group [group_name1] --group [group_name2]